theme: jekyll-theme-cayman
title: FinDo
description: [FinDo est une application qui révolutionne votre manière de pratiquer vos activités]
show_downloads: "false"

  <div class="container-lg p-responsive py-4 py-lg-6 my-xl-4 text-center">
    <h1 class="alt-h1 mb-2 text-white">How agencies build&nbsp;software</h1>
    <p class="f2-light text-white">Collaborate on code, data, policy, or procurement within your agency or with the&nbsp;public.</p>
  </div>
</div><!-- ends .full-width that started in header.html -->
